### ISSUE TITLE
不支持read-only模式

### ISSUE THREAD

**Issue by yejr** [xelabs/benchyou#1]
测试模式：
3个节点的MGR集群，1个读写主节点，2个只读节点。
利用haproxy转发到后端只读服务器。

用下面的测试命令会报错：
benchyou --mysql-host=x --mysql-user=x --mysql-password=x --mysql-port=6001 --oltp-tables-count=64 --mysql-table-engine=innodb --write-threads=0 --read-threads=128 --max-time=60 random

报错信息：
2018/05/10 15:38:18 create.worker.check.database.exec[create database if not exists `sbtest`].error:The MySQL server is running with the --read-only option so it cannot execute this statement (errno 1290) (sqlstate HY000)
panic: create.worker.check.database.exec[create database if not exists `sbtest`].error:The MySQL server is running with the --read-only option so it cannot execute this statement (errno 1290) (sqlstate HY000)

也就是只读请求一开始还是发起 create database if not exists `sbtest` 请求，这样开了read-only后测试会失败，需要关闭 read-only 模式。
mysql> set global super_read_only=0;
mysql> set global read_only=0;

**Comment by yejr** [comment]
顺便多提一下
--mysql-table-engine 参数默认值建议用 innodb 哈。

**Comment by BohuTANG** [comment]
@yejr 

是的，benchyou压测工具目前还不支持只读，后面我们会提供一个参数。
默认参数也会改掉。

**Comment by BohuTANG** [comment]
@yejr 

master分支这个问题修复了，可获取最新版本编译下。

**Comment by yejr** [comment]
赞，神速
