### ISSUE TITLE
diskio busy or not

### ISSUE THREAD

**Issue by Dong-Chan** [xelabs/benchyou#5]
I want to use utilization of diskio for diskio busy or not. But I dont know use total-number for diskio

**Comment by BohuTANG** [comment]
Hello, @Dong-Chan 

benchyou IO metrics are measured by `iostat -x -g ALL 1 2` here:
https://github.com/xelabs/benchyou/blob/master/src/xstat/iostat.go#L56

and the metrics are reported as follows:
```
Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              3.00   10.00     16.00    116.00     0.00    21.00   0.00  67.74    1.33    0.80   0.01     5.33    11.60   0.92   1.20

```
It can't count all the disk IOs here, if you want to check the disk is busy or not, I think the util% is ok.

**Comment by Dong-Chan** [comment]
got it
